import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  weight: '400',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gradient-to-tr from-[#060024] to-[#15007F] h-screen w-screen ${nunito.className} no-scrollbar text-white`}
      >
        {children}
      </body>
    </html>
  );
}
